var peopleArray = [
  {name: 'Ben Zeise', shoutout: 'Thank you for driving me to and from class every day! You have also been very kind and helpful with helping me out with the assignments.' },
  {name: 'Brett Miller', shoutout: 'For being my impromptu partner and having my back.' },
  {name: 'Carl Page', shoutout: '' },
  {name: 'Corey Sader', shoutout: 'Awesome person to work with! Really helpful and friendly. Same goes with Erin' },
  {name: 'Erin Marie Black', shoutout: 'Awesome person to work with! Really helpful and friendly. Same goes with Corey' },
  {name: 'Helena Black', shoutout: '' },
  {name: 'Hogan McDonald', shoutout: 'For walking me through the assignment without giving me the code, which makes me think about what I need to do.' },
  {name: 'Jason Ruby', shoutout: 'Has great tenacity when faced with a problem he doesn\'t know how to solve. Also very resourceful in his approach.' },
  {name: 'Jose Arturo Leyva', shoutout: '' },
  {name: 'Lindsey Olson', shoutout: 'Horray for house plants. Can never have enough. It has been great working with you on the peer assignments.' },
  {name: 'Miles Nelson', shoutout: '' },
  {name: 'Mohamed Mohamed', shoutout: '' },
  {name: 'Moises Hernandez', shoutout: 'Shout out to Moi for all his help with Git/Github and the Blocks Blocks Blocks project!' },
  {name: 'Noah Rolf', shoutout: '' },
  {name: 'Peter Wildberger', shoutout: '' },
  {name: 'Shannon Martin', shoutout: '' },
];
