var peopleArray = [
  {name: 'Abby Sepple', weirdThing: 'Abbey Road and pterodactyl hiccups' },
  {name: 'Alayna Buysse', weirdThing: 'Chucky cheese suit and heard that' },
  {name: 'Amy Venturino', weirdThing: 'No social media and 2 uvulas' },
  {name: 'Barbara King', weirdThing: 'Semi conductor expert and hates touching raw meat' },
  {name: 'Benjimin Lauderbaugh', weirdThing: 'minecraft and sleep walking' },
  {name: 'Charlie Garnaas', weirdThing: 'Morning ice-cream snacking and hates lines' },
  {name: 'Colin James Wymore', weirdThing: 'LOVEs conspiracy theories' },
  {name: 'Droo Hastings', weirdThing: 'Touring musician who craved normalcy' },
  {name: 'Amal Ali', weirdThing: 'Bust out dancing' },
  {name: 'Jim Vang', weirdThing: 'Puts stuff away and lab practical joker' },
  {name: 'Jorge Blue', weirdThing: 'Curious person and had a bit of tree branch in bicep for too long' },
  {name: 'Kara Bayse', weirdThing: 'Collects all the bags and will never eat white castle' },
  {name: 'Matt Larson', weirdThing: 'Experimental everything and collecting things for toy alter' },
  {name: 'Neota Moe', weirdThing: 'Loves watching surgeries, even her own and can talk about gross stuff over dinner' },
  {name: 'Ryan Beadie', weirdThing: 'Hockey hair mullet perm and seven of his favorite shirts' },
  {name: 'Sean Felling', weirdThing: 'Smiles when he is nervous and walks on the outside of his feet' },
  {name: 'Tiffany Love', weirdThing: 'Singing even when she does not realize it and Sunday morning breakfasts' },
  {name: 'Tessa M Ganser', weirdThing: 'Whale drone videos and big family' },
  {name: 'Zeinab Hassan', weirdThing: 'Sweet and savory and Nutella egg breakfasts' }
];
